name: Build project and run tests
on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v6

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: "5.1.1"
        opam-disable-sandboxing: true

    - name: Install dependencies
      run: opam install . --deps-only --with-test

    - name: Build project
      run: opam exec -- dune build

    - name: Run tests
      id: test
      run: |
        ALCOTEST_COLOR=never opam exec -- dune runtest 2> test_results.txt; return 0

    - name: Upload runtest output artifact
      uses: actions/upload-artifact@v7
      with:
          name: alcotest-raw
          path: test_results.txt

    - name: Process test output
      uses: georgejkaye/alcotest-github-action@v1.1.0
      with:
        dune-runtest-input-path: test_results.txt
        test-summary-output-path: alcotest.json

    - name: Upload test results artifact
      uses: actions/upload-artifact@v7
      with:
          name: alcotest-json
          path: alcotest.json

    - name: Public test report
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: alcotest-json
        github-report: true
        upload-artifact: true
        fetch-previous-results: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
